# Generated by Django 3.0.7 on 2020-06-08 11:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiosonde',
            name='dewpointK',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=6), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='radiosonde',
            name='temperatureK',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=6), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='radiosonde',
            name='u_windMS',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=6), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='radiosonde',
            name='v_windMS',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=6), default=list, size=None),
        ),
    ]
